/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AuthorizationListRequestStatus = "closed" | "pending" | "reversed";
export const AuthorizationListRequestStatus = {
    Closed: "closed",
    Pending: "pending",
    Reversed: "reversed",
} as const;
