/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../../../index";

export type SourceDetachResponse = Stripe.PaymentSource | Stripe.DeletedPaymentSource;
