/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CardholderListRequestStatus = "active" | "blocked" | "inactive";
export const CardholderListRequestStatus = {
    Active: "active",
    Blocked: "blocked",
    Inactive: "inactive",
} as const;
