/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface BankAccountVerifyRequest {
    /** Two positive integers, in *cents*, equal to the values of the microdeposits sent to the bank account. */
    amounts?: number[];
    /** Specifies which fields in the response should be expanded. */
    expand?: string[];
}
