/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InboundTransferListRequestStatus = "canceled" | "failed" | "processing" | "succeeded";
export const InboundTransferListRequestStatus = {
    Canceled: "canceled",
    Failed: "failed",
    Processing: "processing",
    Succeeded: "succeeded",
} as const;
