/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface OutboundTransferReturnOutboundTransferRequest {
    /** Specifies which fields in the response should be expanded. */
    expand?: string[];
    /** Details about a returned OutboundTransfer. */
    returned_details?: OutboundTransferReturnOutboundTransferRequest.ReturnedDetails;
}

export namespace OutboundTransferReturnOutboundTransferRequest {
    /**
     * Details about a returned OutboundTransfer.
     */
    export interface ReturnedDetails {
        /** Reason for the return. */
        code?: ReturnedDetails.Code;
    }

    export namespace ReturnedDetails {
        /**
         * Reason for the return.
         */
        export type Code =
            | "account_closed"
            | "account_frozen"
            | "bank_account_restricted"
            | "bank_ownership_changed"
            | "declined"
            | "incorrect_account_holder_name"
            | "invalid_account_number"
            | "invalid_currency"
            | "no_account"
            | "other";
        export const Code = {
            AccountClosed: "account_closed",
            AccountFrozen: "account_frozen",
            BankAccountRestricted: "bank_account_restricted",
            BankOwnershipChanged: "bank_ownership_changed",
            Declined: "declined",
            IncorrectAccountHolderName: "incorrect_account_holder_name",
            InvalidAccountNumber: "invalid_account_number",
            InvalidCurrency: "invalid_currency",
            NoAccount: "no_account",
            Other: "other",
        } as const;
    }
}
