/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         amount: 1,
 *         currency: "currency",
 *         financial_account: "financial_account"
 *     }
 */
export interface ReceivedDebitCreateRequest {
    /** Amount (in cents) to be transferred. */
    amount: number;
    /** Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies). */
    currency: string;
    /** An arbitrary string attached to the object. Often useful for displaying to users. */
    description?: string;
    /** Specifies which fields in the response should be expanded. */
    expand?: string[];
    /** The FinancialAccount to pull funds from. */
    financial_account: string;
    /** Initiating payment method details for the object. */
    initiating_payment_method_details?: ReceivedDebitCreateRequest.InitiatingPaymentMethodDetails;
}

export namespace ReceivedDebitCreateRequest {
    /**
     * Initiating payment method details for the object.
     */
    export interface InitiatingPaymentMethodDetails {
        /** The source type. */
        type: "us_bank_account";
        /** Optional fields for `us_bank_account`. */
        us_bank_account?: InitiatingPaymentMethodDetails.UsBankAccount;
    }

    export namespace InitiatingPaymentMethodDetails {
        /**
         * Optional fields for `us_bank_account`.
         */
        export interface UsBankAccount {
            /** The bank account holder's name. */
            account_holder_name?: string;
            /** The bank account number. */
            account_number?: string;
            /** The bank account's routing number. */
            routing_number?: string;
        }
    }
}
