/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreditNotePreviewLinesRequestEmailType = "credit_note" | "none";
export const CreditNotePreviewLinesRequestEmailType = {
    CreditNote: "credit_note",
    None: "none",
} as const;
