/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface AccountRequirements {
    /** Fields that are due and can be satisfied by providing the corresponding alternative fields instead. */
    alternatives?: Stripe.AccountRequirementsAlternative[];
    /** Date by which the fields in `currently_due` must be collected to keep the account enabled. These fields may disable the account sooner if the next threshold is reached before they are collected. */
    current_deadline?: number;
    /** Fields that need to be collected to keep the account enabled. If not collected by `current_deadline`, these fields appear in `past_due` as well, and the account is disabled. */
    currently_due?: string[];
    /** If the account is disabled, this enum describes why. [Learn more about handling verification issues](https://stripe.com/docs/connect/handling-api-verification). */
    disabled_reason?: AccountRequirements.DisabledReason;
    /** Fields that are `currently_due` and need to be collected again because validation or verification failed. */
    errors?: Stripe.AccountRequirementsError[];
    /** Fields you must collect when all thresholds are reached. As they become required, they appear in `currently_due` as well, and `current_deadline` becomes set. */
    eventually_due?: string[];
    /** Fields that weren't collected by `current_deadline`. These fields need to be collected to enable the account. */
    past_due?: string[];
    /** Fields that might become required depending on the results of verification or review. It's an empty array unless an asynchronous verification is pending. If verification fails, these fields move to `eventually_due`, `currently_due`, or `past_due`. Fields might appear in `eventually_due`, `currently_due`, or `past_due` and in `pending_verification` if verification fails but another verification is still pending. */
    pending_verification?: string[];
}

export namespace AccountRequirements {
    /**
     * If the account is disabled, this enum describes why. [Learn more about handling verification issues](https://stripe.com/docs/connect/handling-api-verification).
     */
    export type DisabledReason =
        | "action_required.requested_capabilities"
        | "listed"
        | "other"
        | "platform_paused"
        | "rejected.fraud"
        | "rejected.incomplete_verification"
        | "rejected.listed"
        | "rejected.other"
        | "rejected.platform_fraud"
        | "rejected.platform_other"
        | "rejected.platform_terms_of_service"
        | "rejected.terms_of_service"
        | "requirements.past_due"
        | "requirements.pending_verification"
        | "under_review";
    export const DisabledReason = {
        ActionRequiredRequestedCapabilities: "action_required.requested_capabilities",
        Listed: "listed",
        Other: "other",
        PlatformPaused: "platform_paused",
        RejectedFraud: "rejected.fraud",
        RejectedIncompleteVerification: "rejected.incomplete_verification",
        RejectedListed: "rejected.listed",
        RejectedOther: "rejected.other",
        RejectedPlatformFraud: "rejected.platform_fraud",
        RejectedPlatformOther: "rejected.platform_other",
        RejectedPlatformTermsOfService: "rejected.platform_terms_of_service",
        RejectedTermsOfService: "rejected.terms_of_service",
        RequirementsPastDue: "requirements.past_due",
        RequirementsPendingVerification: "requirements.pending_verification",
        UnderReview: "under_review",
    } as const;
}
