/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever an external account is created.
 */
export interface AccountExternalAccountCreated {
    object: AccountExternalAccountCreated.Object_;
}

export namespace AccountExternalAccountCreated {
    export type Object_ = Stripe.BankAccount | Stripe.Card | Stripe.Source;
}
