/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * A credit grant is an API resource that documents the allocation of some billing credits to a customer.
 *
 * Related guide: [Billing credits](https://docs.stripe.com/billing/subscriptions/usage-based/billing-credits)
 */
export interface BillingCreditGrant {
    amount: Stripe.BillingCreditGrantsResourceAmount;
    applicability_config: Stripe.BillingCreditGrantsResourceApplicabilityConfig;
    /** The category of this credit grant. This is for tracking purposes and isn't displayed to the customer. */
    category: BillingCreditGrant.Category;
    /** Time at which the object was created. Measured in seconds since the Unix epoch. */
    created: number;
    /** ID of the customer receiving the billing credits. */
    customer: BillingCreditGrant.Customer;
    /** The time when the billing credits become effective-when they're eligible for use. */
    effective_at?: number;
    /** The time when the billing credits expire. If not present, the billing credits don't expire. */
    expires_at?: number;
    /** Unique identifier for the object. */
    id: string;
    /** Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode. */
    livemode: boolean;
    /** Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. */
    metadata: Record<string, string>;
    /** A descriptive name shown in dashboard. */
    name?: string;
    /** String representing the object's type. Objects of the same type share the same value. */
    object: "billing.credit_grant";
    /** ID of the test clock this credit grant belongs to. */
    test_clock?: BillingCreditGrant.TestClock;
    /** Time at which the object was last updated. Measured in seconds since the Unix epoch. */
    updated: number;
    /** The time when this credit grant was voided. If not present, the credit grant hasn't been voided. */
    voided_at?: number;
}

export namespace BillingCreditGrant {
    /**
     * The category of this credit grant. This is for tracking purposes and isn't displayed to the customer.
     */
    export type Category = "paid" | "promotional";
    export const Category = {
        Paid: "paid",
        Promotional: "promotional",
    } as const;
    /**
     * ID of the customer receiving the billing credits.
     */
    export type Customer = string | Stripe.Customer | Stripe.DeletedCustomer;
    /**
     * ID of the test clock this credit grant belongs to.
     */
    export type TestClock = string | Stripe.TestHelpersTestClock;
}
