/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface BillingMeterResourceBillingMeterEventAdjustmentCancel {
    /** Unique identifier for the event. */
    identifier?: string;
}
