/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface BillingMeterResourceBillingMeterStatusTransitions {
    /** The time the meter was deactivated, if any. Measured in seconds since Unix epoch. */
    deactivated_at?: number;
}
