/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface CheckoutSwishPaymentMethodOptions {
    /** The order reference that will be displayed to customers in the Swish application. Defaults to the `id` of the Payment Intent. */
    reference?: string;
}
