/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface CheckoutCardInstallmentsOptions {
    /** Indicates if installments are enabled */
    enabled?: boolean;
}
