/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface ConnectAccountReference {
    /** The connected account being referenced when `type` is `account`. */
    account?: ConnectAccountReference.Account;
    /** Type of the account referenced. */
    type: ConnectAccountReference.Type;
}

export namespace ConnectAccountReference {
    /**
     * The connected account being referenced when `type` is `account`.
     */
    export type Account = string | Stripe.Account;
    /**
     * Type of the account referenced.
     */
    export type Type = "account" | "self";
    export const Type = {
        Account: "account",
        Self: "self",
    } as const;
}
