/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface CouponAppliesTo {
    /** A list of product IDs this coupon applies to */
    products: string[];
}
