/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a coupon is created.
 */
export interface CouponCreated {
    object: Stripe.Coupon;
}
