/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Issue a credit note to adjust an invoice's amount after the invoice is finalized.
 *
 * Related guide: [Credit notes](https://stripe.com/docs/billing/invoices/credit-notes)
 */
export interface CreditNote {
    /** The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax. */
    amount: number;
    /** This is the sum of all the shipping amounts. */
    amount_shipping: number;
    /** Time at which the object was created. Measured in seconds since the Unix epoch. */
    created: number;
    /** Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies). */
    currency: string;
    /** ID of the customer. */
    customer: CreditNote.Customer;
    /** Customer balance transaction related to this credit note. */
    customer_balance_transaction?: CreditNote.CustomerBalanceTransaction;
    /** The integer amount in cents (or local equivalent) representing the total amount of discount that was credited. */
    discount_amount: number;
    /** The aggregate amounts calculated per discount for all line items. */
    discount_amounts: Stripe.DiscountsResourceDiscountAmount[];
    /** The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF. */
    effective_at?: number;
    /** Unique identifier for the object. */
    id: string;
    /** ID of the invoice. */
    invoice: CreditNote.Invoice;
    /** Line items that make up the credit note */
    lines: CreditNote.Lines;
    /** Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode. */
    livemode: boolean;
    /** Customer-facing text that appears on the credit note PDF. */
    memo?: string;
    /** Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. */
    metadata?: Record<string, string | undefined>;
    /** A unique number that identifies this particular credit note and appears on the PDF of the credit note and its associated invoice. */
    number: string;
    /** String representing the object's type. Objects of the same type share the same value. */
    object: "credit_note";
    /** Amount that was credited outside of Stripe. */
    out_of_band_amount?: number;
    /** The link to download the PDF of the credit note. */
    pdf: string;
    /** The pretax credit amounts (ex: discount, credit grants, etc) for all line items. */
    pretax_credit_amounts: Stripe.CreditNotesPretaxCreditAmount[];
    /** Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory` */
    reason?: CreditNote.Reason;
    /** Refund related to this credit note. */
    refund?: CreditNote.Refund;
    /** The details of the cost of shipping, including the ShippingRate applied to the invoice. */
    shipping_cost?: Stripe.InvoicesResourceShippingCost;
    /** Status of this credit note, one of `issued` or `void`. Learn more about [voiding credit notes](https://stripe.com/docs/billing/invoices/credit-notes#voiding). */
    status: CreditNote.Status;
    /** The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding exclusive tax and invoice level discounts. */
    subtotal: number;
    /** The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding all tax and invoice level discounts. */
    subtotal_excluding_tax?: number;
    /** The aggregate amounts calculated per tax rate for all line items. */
    tax_amounts: Stripe.CreditNoteTaxAmount[];
    /** The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax and all discount. */
    total: number;
    /** The integer amount in cents (or local equivalent) representing the total amount of the credit note, excluding tax, but including discounts. */
    total_excluding_tax?: number;
    /** Type of this credit note, one of `pre_payment` or `post_payment`. A `pre_payment` credit note means it was issued when the invoice was open. A `post_payment` credit note means it was issued when the invoice was paid. */
    type: CreditNote.Type;
    /** The time that the credit note was voided. */
    voided_at?: number;
}

export namespace CreditNote {
    /**
     * ID of the customer.
     */
    export type Customer = string | Stripe.Customer | Stripe.DeletedCustomer;
    /**
     * Customer balance transaction related to this credit note.
     */
    export type CustomerBalanceTransaction = string | Stripe.CustomerBalanceTransaction;
    /**
     * ID of the invoice.
     */
    export type Invoice = string | Stripe.Invoice;

    /**
     * Line items that make up the credit note
     */
    export interface Lines {
        /** Details about each object. */
        data: Stripe.CreditNoteLineItem[];
        /** True if this list has another page of items after this one that can be fetched. */
        has_more: boolean;
        /** String representing the object's type. Objects of the same type share the same value. Always has the value `list`. */
        object: "list";
        /** The URL where this list can be accessed. */
        url: string;
    }

    /**
     * Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
     */
    export type Reason = "duplicate" | "fraudulent" | "order_change" | "product_unsatisfactory";
    export const Reason = {
        Duplicate: "duplicate",
        Fraudulent: "fraudulent",
        OrderChange: "order_change",
        ProductUnsatisfactory: "product_unsatisfactory",
    } as const;
    /**
     * Refund related to this credit note.
     */
    export type Refund = string | Stripe.Refund;
    /**
     * Status of this credit note, one of `issued` or `void`. Learn more about [voiding credit notes](https://stripe.com/docs/billing/invoices/credit-notes#voiding).
     */
    export type Status = "issued" | "void";
    export const Status = {
        Issued: "issued",
        Void: "void",
    } as const;
    /**
     * Type of this credit note, one of `pre_payment` or `post_payment`. A `pre_payment` credit note means it was issued when the invoice was open. A `post_payment` credit note means it was issued when the invoice was paid.
     */
    export type Type = "post_payment" | "pre_payment";
    export const Type = {
        PostPayment: "post_payment",
        PrePayment: "pre_payment",
    } as const;
}
