/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferResourceGbBankTransfer {
    /** The last 4 digits of the account number of the sender of the funding. */
    account_number_last4?: string;
    /** The full name of the sender, as supplied by the sending bank. */
    sender_name?: string;
    /** The sort code of the bank of the sender of the funding */
    sort_code?: string;
}
