/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a tax ID is created for a customer.
 */
export interface CustomerTaxIdCreated {
    object: Stripe.TaxId;
}
