/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs when a new Financial Connections account is created.
 */
export interface FinancialConnectionsAccountCreated {
    object: Stripe.FinancialConnectionsAccount;
}
