/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Header data.
 */
export interface ForwardedRequestHeader {
    /** The header name. */
    name: string;
    /** The header value. */
    value: string;
}
