/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * SWIFT Records contain U.S. bank account details per the SWIFT format.
 */
export interface FundingInstructionsBankTransferSwiftRecord {
    account_holder_address: Stripe.Address;
    /** The account holder name */
    account_holder_name: string;
    /** The account number */
    account_number: string;
    /** The account type */
    account_type: string;
    bank_address: Stripe.Address;
    /** The bank name */
    bank_name: string;
    /** The SWIFT code */
    swift_code: string;
}
