/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface FundingInstructionsBankTransfer {
    /** The country of the bank account to fund */
    country: string;
    /** A list of financial addresses that can be used to fund a particular balance */
    financial_addresses: Stripe.FundingInstructionsBankTransferFinancialAddress[];
    /** The bank_transfer type */
    type: FundingInstructionsBankTransfer.Type;
}

export namespace FundingInstructionsBankTransfer {
    /**
     * The bank_transfer type
     */
    export type Type = "eu_bank_transfer" | "jp_bank_transfer";
    export const Type = {
        EuBankTransfer: "eu_bank_transfer",
        JpBankTransfer: "jp_bank_transfer",
    } as const;
}
