/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface GelatoSelfieReportError {
    /** A short machine-readable string giving the reason for the verification failure. */
    code?: GelatoSelfieReportError.Code;
    /** A human-readable message giving the reason for the failure. These messages can be shown to your users. */
    reason?: string;
}

export namespace GelatoSelfieReportError {
    /**
     * A short machine-readable string giving the reason for the verification failure.
     */
    export type Code =
        | "selfie_document_missing_photo"
        | "selfie_face_mismatch"
        | "selfie_manipulated"
        | "selfie_unverified_other";
    export const Code = {
        SelfieDocumentMissingPhoto: "selfie_document_missing_photo",
        SelfieFaceMismatch: "selfie_face_mismatch",
        SelfieManipulated: "selfie_manipulated",
        SelfieUnverifiedOther: "selfie_unverified_other",
    } as const;
}
