/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Result from an id_number check
 */
export interface GelatoIdNumberReport {
    /** Date of birth. */
    dob?: Stripe.GelatoDataIdNumberReportDate;
    /** Details on the verification error. Present when status is `unverified`. */
    error?: Stripe.GelatoIdNumberReportError;
    /** First name. */
    first_name?: string;
    /** ID number. When `id_number_type` is `us_ssn`, only the last 4 digits are present. */
    id_number?: string;
    /** Type of ID number. */
    id_number_type?: GelatoIdNumberReport.IdNumberType;
    /** Last name. */
    last_name?: string;
    /** Status of this `id_number` check. */
    status: GelatoIdNumberReport.Status;
}

export namespace GelatoIdNumberReport {
    /**
     * Type of ID number.
     */
    export type IdNumberType = "br_cpf" | "sg_nric" | "us_ssn";
    export const IdNumberType = {
        BrCpf: "br_cpf",
        SgNric: "sg_nric",
        UsSsn: "us_ssn",
    } as const;
    /**
     * Status of this `id_number` check.
     */
    export type Status = "unverified" | "verified";
    export const Status = {
        Unverified: "unverified",
        Verified: "verified",
    } as const;
}
