/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface InvoicesResourceLineItemsProrationDetails {
    /** For a credit proration `line_item`, the original debit line_items to which the credit proration applies. */
    credited_items?: Stripe.InvoicesResourceLineItemsCreditedItems;
}
