/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface InvoiceItemThresholdReason {
    /** The IDs of the line items that triggered the threshold invoice. */
    line_item_ids: string[];
    /** The quantity threshold boundary that applied to the given line item. */
    usage_gte: number;
}
