/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever an invoice payment attempt requires further user action to complete.
 */
export interface InvoicePaymentActionRequired {
    object: Stripe.Invoice;
}
