/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface InvoiceInstallmentsCard {
    /** Whether Installments are enabled for this Invoice. */
    enabled?: boolean;
}
