/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface InvoicePaymentMethodOptionsBancontact {
    /** Preferred language of the Bancontact authorization page that the customer is redirected to. */
    preferred_language: InvoicePaymentMethodOptionsBancontact.PreferredLanguage;
}

export namespace InvoicePaymentMethodOptionsBancontact {
    /**
     * Preferred language of the Bancontact authorization page that the customer is redirected to.
     */
    export type PreferredLanguage = "de" | "en" | "fr" | "nl";
    export const PreferredLanguage = {
        De: "de",
        En: "en",
        Fr: "fr",
        Nl: "nl",
    } as const;
}
