/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface InvoiceSettingCustomerSetting {
    /** Default custom fields to be displayed on invoices for this customer. */
    custom_fields?: Stripe.InvoiceSettingCustomField[];
    /** ID of a payment method that's attached to the customer, to be used as the customer's default payment method for subscriptions and invoices. */
    default_payment_method?: InvoiceSettingCustomerSetting.DefaultPaymentMethod;
    /** Default footer to be displayed on invoices for this customer. */
    footer?: string;
    /** Default options for invoice PDF rendering for this customer. */
    rendering_options?: Stripe.InvoiceSettingCustomerRenderingOptions;
}

export namespace InvoiceSettingCustomerSetting {
    /**
     * ID of a payment method that's attached to the customer, to be used as the customer's default payment method for subscriptions and invoices.
     */
    export type DefaultPaymentMethod = string | Stripe.PaymentMethod;
}
