/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever an invoice changes (e.g., the invoice amount).
 */
export interface InvoiceUpdated {
    object: Stripe.Invoice;
}
