/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface InvoicePaymentMethodOptionsAcssDebitMandateOptions {
    /** Transaction type of the mandate. */
    transaction_type?: InvoicePaymentMethodOptionsAcssDebitMandateOptions.TransactionType;
}

export namespace InvoicePaymentMethodOptionsAcssDebitMandateOptions {
    /**
     * Transaction type of the mandate.
     */
    export type TransactionType = "business" | "personal";
    export const TransactionType = {
        Business: "business",
        Personal: "personal",
    } as const;
}
