/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface IssuingCardShipping {
    address: Stripe.Address;
    /** Address validation details for the shipment. */
    address_validation?: Stripe.IssuingCardShippingAddressValidation;
    /** The delivery company that shipped a card. */
    carrier?: IssuingCardShipping.Carrier;
    /** Additional information that may be required for clearing customs. */
    customs?: Stripe.IssuingCardShippingCustoms;
    /** A unix timestamp representing a best estimate of when the card will be delivered. */
    eta?: number;
    /** Recipient name. */
    name: string;
    /** The phone number of the receiver of the shipment. Our courier partners will use this number to contact you in the event of card delivery issues. For individual shipments to the EU/UK, if this field is empty, we will provide them with the phone number provided when the cardholder was initially created. */
    phone_number?: string;
    /** Whether a signature is required for card delivery. This feature is only supported for US users. Standard shipping service does not support signature on delivery. The default value for standard shipping service is false and for express and priority services is true. */
    require_signature?: boolean;
    /** Shipment service, such as `standard` or `express`. */
    service: IssuingCardShipping.Service;
    /** The delivery status of the card. */
    status?: IssuingCardShipping.Status;
    /** A tracking number for a card shipment. */
    tracking_number?: string;
    /** A link to the shipping carrier's site where you can view detailed information about a card shipment. */
    tracking_url?: string;
    /** Packaging options. */
    type: IssuingCardShipping.Type;
}

export namespace IssuingCardShipping {
    /**
     * The delivery company that shipped a card.
     */
    export type Carrier = "dhl" | "fedex" | "royal_mail" | "usps";
    export const Carrier = {
        Dhl: "dhl",
        Fedex: "fedex",
        RoyalMail: "royal_mail",
        Usps: "usps",
    } as const;
    /**
     * Shipment service, such as `standard` or `express`.
     */
    export type Service = "express" | "priority" | "standard";
    export const Service = {
        Express: "express",
        Priority: "priority",
        Standard: "standard",
    } as const;
    /**
     * The delivery status of the card.
     */
    export type Status = "canceled" | "delivered" | "failure" | "pending" | "returned" | "shipped" | "submitted";
    export const Status = {
        Canceled: "canceled",
        Delivered: "delivered",
        Failure: "failure",
        Pending: "pending",
        Returned: "returned",
        Shipped: "shipped",
        Submitted: "submitted",
    } as const;
    /**
     * Packaging options.
     */
    export type Type = "bulk" | "individual";
    export const Type = {
        Bulk: "bulk",
        Individual: "individual",
    } as const;
}
