/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a dispute is updated.
 */
export interface IssuingDisputeUpdated {
    object: Stripe.IssuingDispute;
}
