/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface IssuingTransactionAmountDetails {
    /** The fee charged by the ATM for the cash withdrawal. */
    atm_fee?: number;
    /** The amount of cash requested by the cardholder. */
    cashback_amount?: number;
}
