/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface IssuingAuthorizationNetworkData {
    /** Identifier assigned to the acquirer by the card network. Sometimes this value is not provided by the network; in this case, the value will be `null`. */
    acquiring_institution_id?: string;
    /** The System Trace Audit Number (STAN) is a 6-digit identifier assigned by the acquirer. Prefer `network_data.transaction_id` if present, unless you have special requirements. */
    system_trace_audit_number?: string;
    /** Unique identifier for the authorization assigned by the card network used to match subsequent messages, disputes, and transactions. */
    transaction_id?: string;
}
