/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a personalization design is rejected by design review.
 */
export interface IssuingPersonalizationDesignRejected {
    object: Stripe.IssuingPersonalizationDesign;
}
