/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface PaymentLinksResourceConsentCollection {
    /** Settings related to the payment method reuse text shown in the Checkout UI. */
    payment_method_reuse_agreement?: Stripe.PaymentLinksResourcePaymentMethodReuseAgreement;
    /** If set to `auto`, enables the collection of customer consent for promotional communications. */
    promotions?: PaymentLinksResourceConsentCollection.Promotions;
    /** If set to `required`, it requires cutomers to accept the terms of service before being able to pay. If set to `none`, customers won't be shown a checkbox to accept the terms of service. */
    terms_of_service?: PaymentLinksResourceConsentCollection.TermsOfService;
}

export namespace PaymentLinksResourceConsentCollection {
    /**
     * If set to `auto`, enables the collection of customer consent for promotional communications.
     */
    export type Promotions = "auto" | "none";
    export const Promotions = {
        Auto: "auto",
        None: "none",
    } as const;
    /**
     * If set to `required`, it requires cutomers to accept the terms of service before being able to pay. If set to `none`, customers won't be shown a checkbox to accept the terms of service.
     */
    export type TermsOfService = "none" | "required";
    export const TermsOfService = {
        None: "none",
        Required: "required",
    } as const;
}
