/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface PaymentMethodDetailsInteracPresentReceipt {
    /** The type of account being debited or credited */
    account_type?: PaymentMethodDetailsInteracPresentReceipt.AccountType;
    /** EMV tag 9F26, cryptogram generated by the integrated circuit chip. */
    application_cryptogram?: string;
    /** Mnenomic of the Application Identifier. */
    application_preferred_name?: string;
    /** Identifier for this transaction. */
    authorization_code?: string;
    /** EMV tag 8A. A code returned by the card issuer. */
    authorization_response_code?: string;
    /** Describes the method used by the cardholder to verify ownership of the card. One of the following: `approval`, `failure`, `none`, `offline_pin`, `offline_pin_and_signature`, `online_pin`, or `signature`. */
    cardholder_verification_method?: string;
    /** EMV tag 84. Similar to the application identifier stored on the integrated circuit chip. */
    dedicated_file_name?: string;
    /** The outcome of a series of EMV functions performed by the card reader. */
    terminal_verification_results?: string;
    /** An indication of various EMV functions performed during the transaction. */
    transaction_status_information?: string;
}

export namespace PaymentMethodDetailsInteracPresentReceipt {
    /**
     * The type of account being debited or credited
     */
    export type AccountType = "checking" | "savings" | "unknown";
    export const AccountType = {
        Checking: "checking",
        Savings: "savings",
        Unknown: "unknown",
    } as const;
}
