/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface PaymentLinksResourceCompletionBehaviorConfirmationPage {
    /** The custom message that is displayed to the customer after the purchase is complete. */
    custom_message?: string;
}
