/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface PaymentMethodDetailsKakaoPay {
    /** A unique identifier for the buyer as determined by the local payment processor. */
    buyer_id?: string;
}
