/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface PaymentMethodDetailsSepaDebit {
    /** Bank code of bank associated with the bank account. */
    bank_code?: string;
    /** Branch code of bank associated with the bank account. */
    branch_code?: string;
    /** Two-letter ISO code representing the country the bank account is located in. */
    country?: string;
    /** Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same. */
    fingerprint?: string;
    /** Last four characters of the IBAN. */
    last4?: string;
    /** Find the ID of the mandate used for this payment under the [payment_method_details.sepa_debit.mandate](https://stripe.com/docs/api/charges/object#charge_object-payment_method_details-sepa_debit-mandate) property on the Charge. Use this mandate ID to [retrieve the Mandate](https://stripe.com/docs/api/mandates/retrieve). */
    mandate?: string;
}
