/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Indicates the status of a specific payment method on a payment method domain.
 */
export interface PaymentMethodDomainResourcePaymentMethodStatus {
    /** The status of the payment method on the domain. */
    status: PaymentMethodDomainResourcePaymentMethodStatus.Status;
    status_details?: Stripe.PaymentMethodDomainResourcePaymentMethodStatusDetails;
}

export namespace PaymentMethodDomainResourcePaymentMethodStatus {
    /**
     * The status of the payment method on the domain.
     */
    export type Status = "active" | "inactive";
    export const Status = {
        Active: "active",
        Inactive: "inactive",
    } as const;
}
