/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface PaymentIntentNextActionDisplayBankTransferInstructions {
    /** The remaining amount that needs to be transferred to complete the payment. */
    amount_remaining?: number;
    /** Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies). */
    currency?: string;
    /** A list of financial addresses that can be used to fund the customer balance */
    financial_addresses?: Stripe.FundingInstructionsBankTransferFinancialAddress[];
    /** A link to a hosted page that guides your customer through completing the transfer. */
    hosted_instructions_url?: string;
    /** A string identifying this payment. Instruct your customer to include this code in the reference or memo field of their bank transfer. */
    reference?: string;
    /** Type of bank transfer */
    type: PaymentIntentNextActionDisplayBankTransferInstructions.Type;
}

export namespace PaymentIntentNextActionDisplayBankTransferInstructions {
    /**
     * Type of bank transfer
     */
    export type Type =
        | "eu_bank_transfer"
        | "gb_bank_transfer"
        | "jp_bank_transfer"
        | "mx_bank_transfer"
        | "us_bank_transfer";
    export const Type = {
        EuBankTransfer: "eu_bank_transfer",
        GbBankTransfer: "gb_bank_transfer",
        JpBankTransfer: "jp_bank_transfer",
        MxBankTransfer: "mx_bank_transfer",
        UsBankTransfer: "us_bank_transfer",
    } as const;
}
