/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface PaymentLinksResourceTaxIdCollection {
    /** Indicates whether tax ID collection is enabled for the session. */
    enabled: boolean;
    required: PaymentLinksResourceTaxIdCollection.Required;
}

export namespace PaymentLinksResourceTaxIdCollection {
    export type Required = "if_supported" | "never";
    export const Required = {
        IfSupported: "if_supported",
        Never: "never",
    } as const;
}
