/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface PaymentMethodKlarna {
    /** The customer's date of birth, if provided. */
    dob?: Stripe.PaymentFlowsPrivatePaymentMethodsKlarnaDob;
}
