/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface PaymentMethodDetailsWechatPay {
    /** Uniquely identifies this particular WeChat Pay account. You can use this attribute to check whether two WeChat accounts are the same. */
    fingerprint?: string;
    /** Transaction ID of this particular WeChat Pay transaction. */
    transaction_id?: string;
}
