/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface PaymentIntentNextActionKonbini {
    /** The timestamp at which the pending Konbini payment expires. */
    expires_at: number;
    /** The URL for the Konbini payment instructions page, which allows customers to view and print a Konbini voucher. */
    hosted_voucher_url?: string;
    stores: Stripe.PaymentIntentNextActionKonbiniStores;
}
