/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface PaymentMethodOptionsUsBankAccountMandateOptions {
    /** Mandate collection method */
    collection_method?: "paper";
}
