/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface PaymentMethodDetailsAcssDebit {
    /** Name of the bank associated with the bank account. */
    bank_name?: string;
    /** Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same. */
    fingerprint?: string;
    /** Institution number of the bank account */
    institution_number?: string;
    /** Last four digits of the bank account number. */
    last4?: string;
    /** ID of the mandate used to make this payment. */
    mandate?: string;
    /** Transit number of the bank account. */
    transit_number?: string;
}
