/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface PaymentPagesCheckoutSessionConsentCollection {
    /** If set to `hidden`, it will hide legal text related to the reuse of a payment method. */
    payment_method_reuse_agreement?: Stripe.PaymentPagesCheckoutSessionPaymentMethodReuseAgreement;
    /**
     * If set to `auto`, enables the collection of customer consent for promotional communications. The Checkout
     * Session will determine whether to display an option to opt into promotional communication
     * from the merchant depending on the customer's locale. Only available to US merchants.
     */
    promotions?: PaymentPagesCheckoutSessionConsentCollection.Promotions;
    /** If set to `required`, it requires customers to accept the terms of service before being able to pay. */
    terms_of_service?: PaymentPagesCheckoutSessionConsentCollection.TermsOfService;
}

export namespace PaymentPagesCheckoutSessionConsentCollection {
    /**
     * If set to `auto`, enables the collection of customer consent for promotional communications. The Checkout
     * Session will determine whether to display an option to opt into promotional communication
     * from the merchant depending on the customer's locale. Only available to US merchants.
     */
    export type Promotions = "auto" | "none";
    export const Promotions = {
        Auto: "auto",
        None: "none",
    } as const;
    /**
     * If set to `required`, it requires customers to accept the terms of service before being able to pay.
     */
    export type TermsOfService = "none" | "required";
    export const TermsOfService = {
        None: "none",
        Required: "required",
    } as const;
}
