/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface PaypalSellerProtection {
    /** An array of conditions that are covered for the transaction, if applicable. */
    dispute_categories?: PaypalSellerProtection.DisputeCategories.Item[];
    /** Indicates whether the transaction is eligible for PayPal's seller protection. */
    status: PaypalSellerProtection.Status;
}

export namespace PaypalSellerProtection {
    export type DisputeCategories = DisputeCategories.Item[];

    export namespace DisputeCategories {
        export type Item = "fraudulent" | "product_not_received";
        export const Item = {
            Fraudulent: "fraudulent",
            ProductNotReceived: "product_not_received",
        } as const;
    }

    /**
     * Indicates whether the transaction is eligible for PayPal's seller protection.
     */
    export type Status = "eligible" | "not_eligible" | "partially_eligible";
    export const Status = {
        Eligible: "eligible",
        NotEligible: "not_eligible",
        PartiallyEligible: "partially_eligible",
    } as const;
}
