/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a person associated with an account is updated.
 */
export interface PersonUpdated {
    object: Stripe.Person;
}
