/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a promotion code is updated.
 */
export interface PromotionCodeUpdated {
    object: Stripe.PromotionCode;
}
