/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface ReceivedPaymentMethodDetailsFinancialAccount {
    /** The FinancialAccount ID. */
    id: string;
    /** The rails the ReceivedCredit was sent over. A FinancialAccount can only send funds over `stripe`. */
    network: "stripe";
}
