/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a refund is updated.
 */
export interface RefundUpdated {
    object: Stripe.Refund;
}
