/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface RefundDestinationDetailsJpBankTransfer {
    /** The reference assigned to the refund. */
    reference?: string;
    /** Status of the reference on the refund. This can be `pending`, `available` or `unavailable`. */
    reference_status?: string;
}
