/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface RefundDestinationDetailsBlik {
    /** For refunds declined by the network, a decline code provided by the network which indicates the reason the refund failed. */
    network_decline_code?: string;
    /** The reference assigned to the refund. */
    reference?: string;
    /** Status of the reference on the refund. This can be `pending`, `available` or `unavailable`. */
    reference_status?: string;
}
