/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs when a SetupIntent is canceled.
 */
export interface SetupIntentCanceled {
    object: Stripe.SetupIntent;
}
