/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SourceTypeAchDebit {
    bank_name?: string;
    country?: string;
    fingerprint?: string;
    last4?: string;
    routing_number?: string;
    type?: string;
}
