/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Configures how this subscription behaves during the trial period.
 */
export interface SubscriptionsTrialsResourceTrialSettings {
    end_behavior: Stripe.SubscriptionsTrialsResourceEndBehavior;
}
