/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a new subscription schedule is released.
 */
export interface SubscriptionScheduleReleased {
    object: Stripe.SubscriptionSchedule;
}
