/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface TaxProductRegistrationsResourceCountryOptionsEurope {
    standard?: Stripe.TaxProductRegistrationsResourceCountryOptionsEuStandard;
    /** Type of registration in an EU country. */
    type: TaxProductRegistrationsResourceCountryOptionsEurope.Type;
}

export namespace TaxProductRegistrationsResourceCountryOptionsEurope {
    /**
     * Type of registration in an EU country.
     */
    export type Type = "ioss" | "oss_non_union" | "oss_union" | "standard";
    export const Type = {
        Ioss: "ioss",
        OssNonUnion: "oss_non_union",
        OssUnion: "oss_union",
        Standard: "standard",
    } as const;
}
