/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface TaxProductResourceTaxRateDetails {
    /** Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)). */
    country?: string;
    /** The amount of the tax rate when the `rate_type` is `flat_amount`. Tax rates with `rate_type` `percentage` can vary based on the transaction, resulting in this field being `null`. This field exposes the amount and currency of the flat tax rate. */
    flat_amount?: Stripe.TaxRateFlatAmount;
    /** The tax rate percentage as a string. For example, 8.5% is represented as `"8.5"`. */
    percentage_decimal: string;
    /** Indicates the type of tax rate applied to the taxable amount. This value can be `null` when no tax applies to the location. */
    rate_type?: TaxProductResourceTaxRateDetails.RateType;
    /** State, county, province, or region. */
    state?: string;
    /** The tax type, such as `vat` or `sales_tax`. */
    tax_type?: TaxProductResourceTaxRateDetails.TaxType;
}

export namespace TaxProductResourceTaxRateDetails {
    /**
     * Indicates the type of tax rate applied to the taxable amount. This value can be `null` when no tax applies to the location.
     */
    export type RateType = "flat_amount" | "percentage";
    export const RateType = {
        FlatAmount: "flat_amount",
        Percentage: "percentage",
    } as const;
    /**
     * The tax type, such as `vat` or `sales_tax`.
     */
    export type TaxType =
        | "amusement_tax"
        | "communications_tax"
        | "gst"
        | "hst"
        | "igst"
        | "jct"
        | "lease_tax"
        | "pst"
        | "qst"
        | "retail_delivery_fee"
        | "rst"
        | "sales_tax"
        | "service_tax"
        | "vat";
    export const TaxType = {
        AmusementTax: "amusement_tax",
        CommunicationsTax: "communications_tax",
        Gst: "gst",
        Hst: "hst",
        Igst: "igst",
        Jct: "jct",
        LeaseTax: "lease_tax",
        Pst: "pst",
        Qst: "qst",
        RetailDeliveryFee: "retail_delivery_fee",
        Rst: "rst",
        SalesTax: "sales_tax",
        ServiceTax: "service_tax",
        Vat: "vat",
    } as const;
}
