/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever tax settings is updated.
 */
export interface TaxSettingsUpdated {
    object: Stripe.TaxSettings;
}
