/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * A Tax Transaction records the tax collected from or refunded to your customer.
 *
 * Related guide: [Calculate tax in your custom payment flow](https://stripe.com/docs/tax/custom#tax-transaction)
 */
export interface TaxTransaction {
    /** Time at which the object was created. Measured in seconds since the Unix epoch. */
    created: number;
    /** Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies). */
    currency: string;
    /** The ID of an existing [Customer](https://stripe.com/docs/api/customers/object) used for the resource. */
    customer?: string;
    customer_details: Stripe.TaxProductResourceCustomerDetails;
    /** Unique identifier for the transaction. */
    id: string;
    /** The tax collected or refunded, by line item. */
    line_items?: TaxTransaction.LineItems;
    /** Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode. */
    livemode: boolean;
    /** Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. */
    metadata?: Record<string, string | undefined>;
    /** String representing the object's type. Objects of the same type share the same value. */
    object: "tax.transaction";
    /** The Unix timestamp representing when the tax liability is assumed or reduced. */
    posted_at: number;
    /** A custom unique identifier, such as 'myOrder_123'. */
    reference: string;
    /** If `type=reversal`, contains information about what was reversed. */
    reversal?: Stripe.TaxProductResourceTaxTransactionResourceReversal;
    /** The details of the ship from location, such as the address. */
    ship_from_details?: Stripe.TaxProductResourceShipFromDetails;
    /** The shipping cost details for the transaction. */
    shipping_cost?: Stripe.TaxProductResourceTaxTransactionShippingCost;
    /** Timestamp of date at which the tax rules and rates in effect applies for the calculation. */
    tax_date: number;
    /** If `reversal`, this transaction reverses an earlier transaction. */
    type: TaxTransaction.Type;
}

export namespace TaxTransaction {
    /**
     * The tax collected or refunded, by line item.
     */
    export interface LineItems {
        /** Details about each object. */
        data: Stripe.TaxTransactionLineItem[];
        /** True if this list has another page of items after this one that can be fetched. */
        has_more: boolean;
        /** String representing the object's type. Objects of the same type share the same value. Always has the value `list`. */
        object: "list";
        /** The URL where this list can be accessed. */
        url: string;
    }

    /**
     * If `reversal`, this transaction reverses an earlier transaction.
     */
    export type Type = "reversal" | "transaction";
    export const Type = {
        Reversal: "reversal",
        Transaction: "transaction",
    } as const;
}
