/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents a per-transaction override of a reader configuration
 */
export interface TerminalReaderReaderResourceRefundPaymentConfig {
    /** Enable customer initiated cancellation when refunding this payment. */
    enable_customer_cancellation?: boolean;
}
