/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a test clock transitions to a ready status.
 */
export interface TestHelpersTestClockReady {
    object: Stripe.TestHelpersTestClock;
}
