/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface TransformUsage {
    /** Divide usage by this number. */
    divide_by: number;
    /** After division, either round the result `up` or `down`. */
    round: TransformUsage.Round;
}

export namespace TransformUsage {
    /**
     * After division, either round the result `up` or `down`.
     */
    export type Round = "down" | "up";
    export const Round = {
        Down: "down",
        Up: "up",
    } as const;
}
