/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface TreasuryTransactionsResourceFlowDetails {
    credit_reversal?: Stripe.TreasuryCreditReversal;
    debit_reversal?: Stripe.TreasuryDebitReversal;
    inbound_transfer?: Stripe.TreasuryInboundTransfer;
    issuing_authorization?: Stripe.IssuingAuthorization;
    outbound_payment?: Stripe.TreasuryOutboundPayment;
    outbound_transfer?: Stripe.TreasuryOutboundTransfer;
    received_credit?: Stripe.TreasuryReceivedCredit;
    received_debit?: Stripe.TreasuryReceivedDebit;
    /** Type of the flow that created the Transaction. Set to the same value as `flow_type`. */
    type: TreasuryTransactionsResourceFlowDetails.Type;
}

export namespace TreasuryTransactionsResourceFlowDetails {
    /**
     * Type of the flow that created the Transaction. Set to the same value as `flow_type`.
     */
    export type Type =
        | "credit_reversal"
        | "debit_reversal"
        | "inbound_transfer"
        | "issuing_authorization"
        | "other"
        | "outbound_payment"
        | "outbound_transfer"
        | "received_credit"
        | "received_debit";
    export const Type = {
        CreditReversal: "credit_reversal",
        DebitReversal: "debit_reversal",
        InboundTransfer: "inbound_transfer",
        IssuingAuthorization: "issuing_authorization",
        Other: "other",
        OutboundPayment: "outbound_payment",
        OutboundTransfer: "outbound_transfer",
        ReceivedCredit: "received_credit",
        ReceivedDebit: "received_debit",
    } as const;
}
