/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface TreasuryOutboundTransfersResourceAchTrackingDetails {
    /** ACH trace ID of the OutboundTransfer for transfers sent over the `ach` network. */
    trace_id: string;
}
