/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a received_credit transitions to succeeded state. Only applicable for check deposits.
 */
export interface TreasuryReceivedCreditSucceeded {
    object: Stripe.TreasuryReceivedCredit;
}
