/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface TreasuryReceivedDebitsResourceStatusTransitions {
    /** Timestamp describing when the DebitReversal changed status to `completed`. */
    completed_at?: number;
}
