/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows {
    /** If funds for this flow were returned after the flow went to the `succeeded` state, this field contains a reference to the ReceivedDebit return. */
    received_debit?: string;
}
