/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions {
    /** Timestamp describing when an OutboundPayment changed status to `canceled`. */
    canceled_at?: number;
    /** Timestamp describing when an OutboundPayment changed status to `failed`. */
    failed_at?: number;
    /** Timestamp describing when an OutboundPayment changed status to `posted`. */
    posted_at?: number;
    /** Timestamp describing when an OutboundPayment changed status to `returned`. */
    returned_at?: number;
}
