/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever the status of the FinancialAccount becomes closed.
 */
export interface TreasuryFinancialAccountClosed {
    object: Stripe.TreasuryFinancialAccount;
}
