/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever a received_credit is created as a result of funds being pushed by another account.
 */
export interface TreasuryReceivedCreditCreated {
    object: Stripe.TreasuryReceivedCredit;
}
