/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever an InboundTransfer has succeeded.
 */
export interface TreasuryInboundTransferSucceeded {
    object: Stripe.TreasuryInboundTransfer;
}
