/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount {
    /** Bank name. */
    bank_name?: string;
    /** The last four digits of the bank account number. */
    last4?: string;
    /** The routing number for the bank account. */
    routing_number?: string;
}
