/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Occurs whenever an OutboundPayment is canceled.
 */
export interface TreasuryOutboundPaymentCanceled {
    object: Stripe.TreasuryOutboundPayment;
}
