/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 *
 */
export interface TreasuryOutboundTransfersResourceReturnedDetails {
    /** Reason for the return. */
    code: TreasuryOutboundTransfersResourceReturnedDetails.Code;
    /** The Transaction associated with this object. */
    transaction: TreasuryOutboundTransfersResourceReturnedDetails.Transaction;
}

export namespace TreasuryOutboundTransfersResourceReturnedDetails {
    /**
     * Reason for the return.
     */
    export type Code =
        | "account_closed"
        | "account_frozen"
        | "bank_account_restricted"
        | "bank_ownership_changed"
        | "declined"
        | "incorrect_account_holder_name"
        | "invalid_account_number"
        | "invalid_currency"
        | "no_account"
        | "other";
    export const Code = {
        AccountClosed: "account_closed",
        AccountFrozen: "account_frozen",
        BankAccountRestricted: "bank_account_restricted",
        BankOwnershipChanged: "bank_ownership_changed",
        Declined: "declined",
        IncorrectAccountHolderName: "incorrect_account_holder_name",
        InvalidAccountNumber: "invalid_account_number",
        InvalidCurrency: "invalid_currency",
        NoAccount: "no_account",
        Other: "other",
    } as const;
    /**
     * The Transaction associated with this object.
     */
    export type Transaction = string | Stripe.TreasuryTransaction;
}
