/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Stripe from "../index";

/**
 * Encodes whether a FinancialAccount has access to a particular Feature, with a `status` enum and associated `status_details`.
 * Stripe or the platform can control Features via the requested field.
 */
export interface TreasuryFinancialAccountFeatures {
    card_issuing?: Stripe.TreasuryFinancialAccountsResourceToggleSettings;
    deposit_insurance?: Stripe.TreasuryFinancialAccountsResourceToggleSettings;
    financial_addresses?: Stripe.TreasuryFinancialAccountsResourceFinancialAddressesFeatures;
    inbound_transfers?: Stripe.TreasuryFinancialAccountsResourceInboundTransfers;
    intra_stripe_flows?: Stripe.TreasuryFinancialAccountsResourceToggleSettings;
    /** String representing the object's type. Objects of the same type share the same value. */
    object: "treasury.financial_account_features";
    outbound_payments?: Stripe.TreasuryFinancialAccountsResourceOutboundPayments;
    outbound_transfers?: Stripe.TreasuryFinancialAccountsResourceOutboundTransfers;
}
