/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export interface UsBankAccountNetworks {
    /** The preferred network. */
    preferred?: string;
    /** All supported networks. */
    supported: UsBankAccountNetworks.Supported.Item[];
}

export namespace UsBankAccountNetworks {
    export type Supported = Supported.Item[];

    export namespace Supported {
        export type Item = "ach" | "us_domestic_wire";
        export const Item = {
            Ach: "ach",
            UsDomesticWire: "us_domestic_wire",
        } as const;
    }
}
