/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface AuthorizationReverseRequest {
    /** Specifies which fields in the response should be expanded. */
    expand?: string[];
    /** The amount to reverse from the authorization. If not provided, the full amount of the authorization will be reversed. This amount is in the authorization currency and in the [smallest currency unit](https://stripe.com/docs/currencies#zero-decimal). */
    reverse_amount?: number;
}
