/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface SourceRetrieveRequest {
    /**
     * The client secret of the source. Required if a publishable key is used to retrieve the source.
     */
    client_secret?: string;
    /**
     * Specifies which fields in the response should be expanded.
     */
    expand?: string | string[];
}
