/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreditBalanceSummaryRetrieveRequestFilter {
    /** The billing credit applicability scope for which to fetch credit balance summary. */
    applicability_scope?: CreditBalanceSummaryRetrieveRequestFilter.ApplicabilityScope;
    /** The credit grant for which to fetch credit balance summary. */
    credit_grant?: string;
    /** Specify the type of this filter. */
    type: CreditBalanceSummaryRetrieveRequestFilter.Type;
}

export namespace CreditBalanceSummaryRetrieveRequestFilter {
    /**
     * The billing credit applicability scope for which to fetch credit balance summary.
     */
    export interface ApplicabilityScope {
        /** The price type that credit grants can apply to. We currently only support the `metered` price type. */
        price_type: "metered";
    }

    /**
     * Specify the type of this filter.
     */
    export type Type = "applicability_scope" | "credit_grant";
    export const Type = {
        ApplicabilityScope: "applicability_scope",
        CreditGrant: "credit_grant",
    } as const;
}
