/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InvoiceUpcomingLinesRequestOnBehalfOf = "";
export const InvoiceUpcomingLinesRequestOnBehalfOf = {
    Empty: "",
} as const;
