/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entitlement_feature: "entitlement_feature"
 *     }
 */
export interface ProductFeatureCreateRequest {
    /** The ID of the [Feature](https://stripe.com/docs/api/entitlements/feature) object attached to this product. */
    entitlement_feature: string;
    /** Specifies which fields in the response should be expanded. */
    expand?: string[];
}
