/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReceivedCreditListRequestStatus = "failed" | "succeeded";
export const ReceivedCreditListRequestStatus = {
    Failed: "failed",
    Succeeded: "succeeded",
} as const;
