/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface PersonalizationDesignActivateRequest {
    /** Specifies which fields in the response should be expanded. */
    expand?: string[];
}
