/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DebitReversalListRequestStatus = "canceled" | "completed" | "processing";
export const DebitReversalListRequestStatus = {
    Canceled: "canceled",
    Completed: "completed",
    Processing: "processing",
} as const;
